name: HawkScan Run

on:
  workflow_dispatch:   # allows manual runs
  push:                # runs on commit (push) events
    branches: [ "main" ]   # restrict to main branch; remove this line to run on all branches

permissions:
  # required for all workflows
  security-events: write
  # required to fetch internal or private CodeQL packs
  packages: read
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run JavaSpringVulny (slower)
        run: docker compose build && docker compose up -d

      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml
        env:
          # APP_ID: ${{ secrets.appId }}
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
