name:  HawkScan
on:
  push: 
    branches:
      - main
  pull_request:
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create $GITHUB_REPOSITORY app directory
        run: mkdir -p common/build/integrationTests/hawkscan-action/apps/$GITHUB_REPOSITORY
      - name: Navigate to $GITHUB_REPOSITORY app directory
        run: cd common/build/integrationTests/hawkscan-action/apps/$GITHUB_REPOSITORY
      - name: Checkout vulny repo
        run: git clone https://github.com/$GITHUB_REPOSITORY.git
      - name: Run $GITHUB_REPOSITORY
        run: docker-compose up -d
      - name: Navigate to repo root directory
        run: cd /home/runner/work/$GITHUB_REPOSITORY/$GITHUB_REPOSITORY
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: ${{ github.event.client_payload.configFile }}
          sourceURL: ${{ github.event.client_payload.hawkscanSourceUrl }}
          version: ${{ github.event.client_payload.hawkscanVersion }}
          verbose: ${{ github.event.client_payload.verbose }}
        env:
          # APPLICATION_ID: ${{ github.event.client_payload.appId }}
          APP_ID: ${{ github.event.client_payload.appId }}
